#!/bin/bash
# Autor: Jrohy
# github: https://github.com/Jrohy/multi-v2ray

# Registra o caminho inicial ao executar o script
begin_path=$(pwd)

# Método de instalação, 0 para instalação completa, 1 para atualizar mantendo a configuração do v2ray
install_way=0

# Define variáveis de operação, 0 para não, 1 para sim
help=0

remove=0

chinese=0

base_source_path="https://multi.netlify.app"

util_path="/etc/v2ray_util/util.cfg"

util_cfg="$base_source_path/v2ray_util/util_core/util.cfg"

bash_completion_shell="$base_source_path/v2ray"

clean_iptables_shell="$base_source_path/v2ray_util/global_setting/clean_iptables.sh"

# Centos desativa temporariamente alias
[[ -f /etc/redhat-release && -z $(echo $SHELL|grep zsh) ]] && unalias -a

[[ -z $(echo $SHELL|grep zsh) ]] && env_file=".bashrc" || env_file=".zshrc"

####### Código de cor ########
red="31m"
green="32m"
yellow="33m"
blue="36m"
fuchsia="35m"

colorEcho(){
    color=$1
    echo -e "\033[${color}${@:2}\033[0m"
}

####### Obter parâmetros #########
while [[ $# > 0 ]];do
    key="$1"
    case $key in
        --remove)
        remove=1
        ;;
        -h|--help)
        help=1
        ;;
        -k|--keep)
        install_way=1
        colorEcho ${blue} "manter configuração para atualizar\n"
        ;;
        --zh)
        chinese=1
        colorEcho ${blue} "Instalando versão em chinês..\n"
        ;;
        *)
                # opção desconhecida
        ;;
    esac
    shift # passa para o próximo argumento ou valor
done
#############################

help(){
    echo "bash v2ray.sh [-h|--help] [-k|--keep] [--remove]"
    echo "  -h, --help           Exibir ajuda"
    echo "  -k, --keep           Manter o config.json para atualizar"
    echo "      --remove         Remover v2ray, xray e multi-v2ray"
    echo "                       Sem parâmetros para instalação nova"
    return 0
}

removeV2Ray() {
    # Desinstalar script do V2Ray
    bash <(curl -L -s https://multi.netlify.app/go.sh) --remove >/dev/null 2>&1
    rm -rf /etc/v2ray >/dev/null 2>&1
    rm -rf /var/log/v2ray >/dev/null 2>&1

    # Desinstalar script do XRay
    bash <(curl -L -s https://multi.netlify.app/go.sh) --remove -x >/dev/null 2>&1
    rm -rf /etc/xray >/dev/null 2>&1
    rm -rf /var/log/xray >/dev/null 2>&1

    # Limpar regras relacionadas ao V2Ray no iptables
    bash <(curl -L -s $clean_iptables_shell)

    # Desinstalar multi-v2ray
    pip uninstall v2ray_util -y
    rm -rf /usr/share/bash-completion/completions/v2ray.bash >/dev/null 2>&1
    rm -rf /usr/share/bash-completion/completions/v2ray >/dev/null 2>&1
    rm -rf /usr/share/bash-completion/completions/xray >/dev/null 2>&1
    rm -rf /etc/bash_completion.d/v2ray.bash >/dev/null 2>&1
    rm -rf /usr/local/bin/v2ray >/dev/null 2>&1
    rm -rf /etc/v2ray_util >/dev/null 2>&1
    rm -rf /etc/profile.d/iptables.sh >/dev/null 2>&1
    rm -rf /root/.iptables >/dev/null 2>&1

    # Remover tarefa agendada de atualização do V2Ray
    crontab -l|sed '/SHELL=/d;/v2ray/d'|sed '/SHELL=/d;/xray/d' > crontab.txt
    crontab crontab.txt >/dev/null 2>&1
    rm -f crontab.txt >/dev/null 2>&1

    if [[ ${package_manager} == 'dnf' || ${package_manager} == 'yum' ]];then
        systemctl restart crond >/dev/null 2>&1
    else
        systemctl restart cron >/dev/null 2>&1
    fi

    # Remover variáveis de ambiente do multi-v2ray
    sed -i '/v2ray/d' ~/$env_file
    sed -i '/xray/d' ~/$env_file
    source ~/$env_file

    rc_service=`systemctl status rc-local|grep loaded|egrep -o "[A-Za-z/]+/rc-local.service"`

    rc_file=`cat $rc_service|grep ExecStart|awk '{print $1}'|cut -d = -f2`

    sed -i '/iptables/d' ~/$rc_file

    colorEcho ${green} "desinstalação concluída com sucesso!"
}

closeSELinux() {
    # Desabilitar SELinux
    if [ -s /etc/selinux/config ] && grep 'SELINUX=enforcing' /etc/selinux/config; then
        sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config
        setenforce 0
    fi
}

checkSys() {
    # Verifica se é Root
    [ $(id -u) != "0" ] && { colorEcho ${red} "Erro: Você deve ser root para executar este script"; exit 1; }

    if [[ `command -v apt-get` ]];then
        package_manager='apt-get'
    elif [[ `command -v dnf` ]];then
        package_manager='dnf'
    elif [[ `command -v yum` ]];then
        package_manager='yum'
    else
        colorEcho $red "Sistema operacional não suportado!"
        exit 1
    fi
}

# Instalar dependências
installDependent(){
    if [[ ${package_manager} == 'dnf' || ${package_manager} == 'yum' ]];then
        ${package_manager} install socat crontabs bash-completion which -y
    else
        ${package_manager} update
        ${package_manager} install socat cron bash-completion ntpdate gawk -y
    fi

    # Instalar python3 e pip
    source <(curl -sL https://python3.netlify.app/install.sh)
}

updateProject() {
    [[ ! $(type pip 2>/dev/null) ]] && colorEcho $red "pip não instalado!" && exit 1

    [[ -e /etc/profile.d/iptables.sh ]] && rm -f /etc/profile.d/iptables.sh

    rc_service=`systemctl status rc-local|grep loaded|egrep -o "[A-Za-z/]+/rc-local.service"`

    rc_file=`cat $rc_service|grep ExecStart|awk '{print $1}'|cut -d = -f2`

    if [[ ! -e $rc_file || -z `cat $rc_file|grep iptables` ]];then
        local_ip=`curl -s http://api.ipify.org 2>/dev/null`
        [[ `echo $local_ip|grep :` ]] && iptable_way="ip6tables" || iptable_way="iptables" 
        if [[ ! -e $rc_file || -z `cat $rc_file|grep "/bin/bash"` ]];then
            echo "#!/bin/bash" >> $rc_file
        fi
        if [[ -z `cat $rc_service|grep "\[Install\]"` ]];then
            cat >> $rc_service << EOF

[Install]
WantedBy=multi-user.target
EOF
            systemctl daemon-reload
        fi
        echo "[[ -e /root/.iptables ]] && $iptable_way-restore -c < /root/.iptables" >> $rc_file
        chmod +x $rc_file
        systemctl restart rc-local
        systemctl enable rc-local

        $iptable_way-save -c > /root/.iptables
    fi

    pip install -U v2ray_util

    if [[ -e $util_path ]];then
        [[ -z $(cat $util_path|grep lang) ]] && echo "lang=en" >> $util_path
    else
        mkdir -p /etc/v2ray_util
        curl $util_cfg > $util_path
    fi

    [[ $chinese == 1 ]] && sed -i "s/lang=en/lang=zh/g" $util_path

    rm -f /usr/local/bin/v2ray >/dev/null 2>&1
    ln -s $(which v2ray-util) /usr/local/bin/v2ray
    rm -f /usr/local/bin/xray >/dev/null 2>&1
    ln -s $(which v2ray-util) /usr/local/bin/xray

    # Remover script antigo de conclusão automática
    rm -f /usr/share/bash-completion/completions/v2ray.bash >/dev/null 2>&1
    curl -o /usr/share/bash-completion/completions/v2ray $bash_completion_shell
    cp /usr/share/bash-completion/completions/v2ray /usr/share/bash-completion/completions/xray >/dev/null 2>&1
}

timeSync() {
    systemctl stop ntp >/dev/null 2>&1
    ntpdate pool.ntp.org
}

profileInit() {
    sed -i '/v2ray/d' ~/$env_file
    sed -i '/xray/d' ~/$env_file

    echo "export PATH=\$PATH:/usr/local/bin/v2ray" >> ~/$env_file
    echo "export PATH=\$PATH:/usr/local/bin/xray" >> ~/$env_file
    source ~/$env_file
}

installFinish() {
    [[ $chinese == 1 ]] && curl https://raw.githubusercontent.com/Jrohy/multi-v2ray/master/thank_you | sed 's/多协议/多协议支持，提供 v2ray，trojan，shadowsocks，xray，一键自动化安装与配置/' || curl https://raw.githubusercontent.com/Jrohy/multi-v2ray/master/thank_you
    colorEcho ${green} "Conclusão da instalação!\n"
}

main() {
    [[ ${help} == 1 ]] && help && exit 0

    [[ ${remove} == 1 ]] && removeV2Ray && exit 0

    checkSys

    closeSELinux

    installDependent

    timeSync

    updateProject

    profileInit

    installFinish

    cd $begin_path
}

main
