#!/bin/bash

# Definir variáveis para cores de texto
VERMELHO='\033[1;31m'
VERDE='\033[1;32m'
AMARELO='\033[1;33m'
CINZA='\033[1;37m'
RESET='\033[0m'

# Função para barra de progresso
fun_bar() {
    comando[0]="$1"
    comando[1]="$2"
    (
        [[ -e $HOME/fim ]] && rm $HOME/fim
        ${comando[0]} -y > /dev/null 2>&1
        ${comando[1]} -y > /dev/null 2>&1
        touch $HOME/fim
    ) > /dev/null 2>&1 &
    tput civis
    echo -ne "  ${AMARELO}AGUARDE ${CINZA}- ${AMARELO}["
    while true; do
        for ((i = 0; i < 18; i++)); do
            echo -ne "${VERMELHO}#"
            sleep 0.1s
        done
        [[ -e $HOME/fim ]] && rm $HOME/fim && break
        echo -e "${AMARELO}]"
        sleep 1s
        tput cuu1
        tput dl1
        echo -ne "  ${AMARELO}AGUARDE ${CINZA}- ${AMARELO}["
    done
    echo -e "${AMARELO}]${CINZA} -${VERDE} OK!${RESET}"
    tput cnorm
}

# Limpar a tela
clear
echo -e "${CINZA}[${VERMELHO}-${CINZA}]${VERMELHO} ───────────────── /// ────────────────── ${AMARELO}"
figlet -p -f slant SlowDNS
echo -e "${CINZA}[${VERMELHO}-${CINZA}]${VERMELHO} ────────────── Instalador ────────────── ${AMARELO}"
echo ""
echo -e "      Este script fará a instalação"
echo -e "      do modo de conexão SlowDNS."
echo ""
echo -e "${CINZA}[${VERMELHO}-${CINZA}]${VERMELHO} ───────────────── /// ────────────────── ${AMARELO}"
echo ""

# Baixando dependências
echo -e "BAIXANDO DEPENDÊNCIAS..."
fun_att() {
    apt update -y
    apt install ncurses-utils -y
    mkdir -p /etc/slowdns
    cd /etc/slowdns
    wget -q https://github.com/PhoenixxZ2023/PLUS/main/Slowdns/{dns-server,remove-slow,slowdns-info,slowdns-drop,slowdns-ssh,slowdns-ssl,slowdns-socks,slowdns-customservice,stopdns} -P .
    chmod +x *
    wget -qO /usr/bin/slowdns https://github.com/PhoenixxZ2023/PLUS/main/Slowdns/slowdns
    chmod +x /usr/bin/slowdns
}
fun_bar fun_att

# Configurando firewall
echo -e "CONFIGURANDO FIREWALL..."
fun_ports() {
    apt install firewalld -y
    firewall-cmd --zone=public --permanent --add-port=53/udp --add-port=5300/udp \
        --add-port=80/tcp --add-port=443/tcp --add-port=8080/tcp \
        --add-port=85/tcp --add-port=2222/tcp
    firewall-cmd --reload
}
fun_bar fun_ports

# Configurando DNS Cloudflare
echo -e "CONFIGURANDO DNS CLOUDFLARE..."
fun_dnscf() {
    systemctl disable systemd-resolved.service
    systemctl stop systemd-resolved.service
    mv /etc/resolv.conf /etc/resolv.conf.bkp
    echo "nameserver 1.1.1.1" > /etc/resolv.conf
    systemctl enable systemd-resolved.service
    systemctl start systemd-resolved.service
}
fun_bar fun_dnscf

# Finalizando
clear
echo -e "${CINZA}[${VERMELHO}-${CINZA}]${VERMELHO} ───────────────── /// ────────────────── ${AMARELO}"
figlet -p -f slant SlowDNS
echo -e "${CINZA}[${VERMELHO}-${CINZA}]${VERMELHO} ────────────── Instalador ────────────── ${AMARELO}"
echo ""
echo -e "          ${AMARELO}INSTALAÇÃO CONCLUÍDA${RESET}        "
echo ""
echo -e "Para abrir o menu, utilize o comando: ${VERMELHO}slowdns${RESET}"
cd
sleep 3
slowdns
