#!/bin/bash
clear
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
tput setaf 7 ; tput bold ; printf '%40s%s%-12s\n' "INSTALANDO SERVIÇO PERSONALIZADO SLOWDNS" ; tput sgr0
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo -e ""
echo -e "      Este script vai instalar o"
echo -e " slowdns para tunelamento de DNS com um Serviço Personalizado."
echo -e ""
echo -e "         \033[1;33mInstalador Mod VpsPack \033[1;37m"
echo -e ""
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo ""
echo -e "ATUALIZANDO LISTA DE PACOTES..."
fun_att () {
apt update && apt upgrade -y
}
fun_bar 'fun_att'
echo -e "INSTALANDO E ATUALIZANDO PACOTES NECESSÁRIOS..."
install_pkgs () {
apt install screen -y
apt install cron -y
apt install iptables -y
service cron reload
service cron restart
service iptables reload
service iptables restart
}
fun_bar 'install_pkgs'
echo -e "CONFIGURANDO IPTABLES..."
ipt_set () {
cd /etc
mv rc.local rc.local.bkp
wget https://github.com/PhoenixxZ2023/PLUS/raw/main/Slowdns/rc.local
chmod +x /etc/rc.local
systemctl enable rc-local
systemctl start rc-local
}
fun_bar 'ipt_set'
clear
echo ""
echo -e "\033[1;31m ATENÇÃO NESTA ETAPA! \033[1;33m"
echo ""
echo -ne "\033[1;32m DIGITE SEU NS (NAMESERVER)\033[1;37m: "; read nameserver
cd /etc/slowdns
touch infons
echo $nameserver > infons
sleep 1
cd /etc/slowdns
echo ""
echo -ne "\033[1;32m DIGITE A PORTA DO SERVIÇO PARA USAR COM SLOWDNS (NÃO 53/5300)\033[1;37m: "
read customservice
if [[ "$customservice" == "53" || "$customservice" == "5300" ]]; then
    echo -e "\033[1;31m ERRO: A PORTA NÃO PODE SER 53 NEM 5300. \033[0m"
    exit 1
fi
cat <<EOF > /etc/slowdns/startdns
#!/bin/bash
echo "INICIANDO SLOWDNS"
screen -dmS slowdns$customservice /etc/slowdns/dns-server -udp :5300 -privkey-file /root/server.key $nameserver 127.0.0.1:$customservice
echo ""
echo "       SLOWDNS INICIADO COM SUCESSO!!!"
EOF
cat <<EOF > /etc/slowdns/restartdns
#!/bin/bash
echo "REINICIANDO SLOWDNS"
screen -ls | grep slowdns | cut -d. -f1 | awk '{print \$1}' | xargs kill
screen -dmS slowdns$customservice /etc/slowdns/dns-server -udp :5300 -privkey-file /root/server.key $nameserver 127.0.0.1:$customservice
echo ""
echo "SlowDNS Reiniciado com Sucesso! [✔]"
EOF
set_ns () {
chmod +x /etc/slowdns/startdns
chmod +x /etc/slowdns/restartdns
cp startdns /bin/
cp restartdns /bin/
}
fun_bar 'set_ns'
echo ""
echo "Verificando a existência da chave"
sleep 2
echo ""
echo "      Aguarde...  "
sleep 2
cd
key1="/root/server.key"
key2="/root/server.pub"
if [ -f $key1 ] && [ -f $key2 ]
then
echo -e "ARQUIVO DE CHAVE ENCONTRADO!"
sleep 1
echo ""
key () {
echo -e "\033[1;33mCOMO VOCÊ GOSTARIA DE OBTER SUA CHAVE?\033[0m"
echo ""
echo -e "\033[1;33m[ 1 ]\033[0m | \033[1;37mUSAR CHAVE EXISTENTE NO ARQUIVO\033[0m"
echo -e "\033[1;33m[ 2 ]\033[0m | \033[1;37mDELETAR ARQUIVO E GERAR NOVA CHAVE\033[0m"
echo -e "\033[1;33m[ 3 ]\033[0m | \033[1;37mDELETAR ARQUIVO E USAR CHAVE PADRÃO\033[0m"
echo -e "\033[1;33m[ X ]\033[0m | \033[1;37mABORTAR INSTALAÇÃO\033[0m"
echo ""
echo -ne "\033[1;33mDIGITE UMA OPÇÃO:\033[0m " && read option
case $option in
1) Option1 ;;
2) Option2 ;;
3) Option3 ;;
x) OptionX ;;
*) echo -e "\033[1;31mCOMANDO DESCONHECIDO\033[0m" ; echo ; key;;
esac
}
Option1 () {
echo -ne "RESTAURO DA CHAVE EXISTENTE..." && sleep 2 && echo "OK!"
echo ""
echo -e "FINALIZANDO..."
finish_ist () {
cd /etc/slowdns
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
}
fun_bar 'finish_ist'
clear
echo -e "\033[1;31mINSTALAÇÃO CONCLUÍDA!\033[0m"
echo ""
echo -ne "\033[1;33mSEU NS:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;33mSUA CHAVE PÚBLICA:\033[0m " && cat /root/server.pub
echo ""
echo -e "\033[1;33mSUA CHAVE ESTÁ SALVA NO ARQUIVO /root/server.pub\033[0m"
echo -e "\033[1;33mMANTENHA-A EM UM LOCAL SEGURO, VOCÊ PODE PRECISAR DELA NO FUTURO!\033[0m"
echo ""
read -p "Pressione [Enter] para voltar ao menu ou CTRL+C para sair"
slowdns
}
Option2 () {
cd
rm server.key server.pub
echo "GERANDO NOVA CHAVE"
cd /etc/slowdns/
./dns-server -gen-key -privkey-file /root/server.key -pubkey-file /root/server.pub
echo -e "FINALIZANDO..."
finish_ist () {
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
cd
}
fun_bar 'finish_ist'
clear
echo -e "\033[1;31m INSTALAÇÃO CONCLUÍDA!\033[0m"
echo ""
echo -ne "\033[1;33mSEU NS:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;33mSUA CHAVE PÚBLICA:\033[0m " && cat /root/server.pub
echo ""
echo -e "\033[1;33m SUA CHAVE ESTÁ SALVA NO ARQUIVO /root/server.pub\033[0m"
echo -e "\033[1;33mMANTENHA-A EM UM LOCAL SEGURO, VOCÊ PODE PRECISAR DELA NO FUTURO!\033[0m"
echo ""
read -p "Pressione [Enter] para voltar ao menu ou CTRL+C para sair"
slowdns
}
Opcao3 () {
echo -e "BAIXANDO PAR DE CHAVES PADRÃO..."
cd
rm server.key server.pub
wget https://raw.githubusercontent.com/PhoenixxZ2023/PLUS/main/Slowdns/server.key
wget https://raw.githubusercontent.com/PhoenixxZ2023/PLUS/main/Slowdns/server.pub
sleep 1
echo -e "Download Concluído"
sleep 1
cd /etc/slowdns/
echo -e "FINALIZANDO..."
finish_ist () {
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
cd
}
fun_bar 'finish_ist'
clear
echo -e "\033[1;31m INSTALAÇÃO CONCLUÍDA!\033[0m"
echo ""
echo -ne "\033[1;33mSEU NS:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;33mSUA CHAVE PÚBLICA:\033[0m " && cat /root/server.pub
echo ""
echo -e "\033[1;33m SUA CHAVE ESTÁ SALVA NO ARQUIVO /root/server.pub\033[0m"
echo -e "\033[1;33mMANTENHA-A EM UM LOCAL SEGURO, VOCÊ PODE PRECISAR DELA NO FUTURO!\033[0m"
echo ""
read -p "Pressione [Enter] para voltar ao menu ou CTRL+C para sair"
slowdns
}
OptionX () {
exit
}
key
else
echo -e "NÃO HÁ CHAVE NOS REGISTROS"
echo ""
key_gen () {
echo "COMO VOCÊ DESEJA OBTER SUA CHAVE?"
echo ""
echo "[ 1 ] | Gerar durante a instalação"
echo "[ 2 ] | Usar a chave padrão"
echo "[ x ] | Abortar instalação"
echo ""
echo -ne "Digite uma opção: " && read opc_key
case $opc_key in
1) opc_key1 ;;
2) opc_key2 ;;
x) opc_keyx ;;
*) "Comando desconhecido" ; echo ; key_gen;;
esac
}
opc_key1 () {
echo "Gerando sua chave..."
cd /etc/slowdns/
./dns-server -gen-key -privkey-file /root/server.key -pubkey-file /root/server.pub
echo -e "FINALIZANDO..."
finish_ist () {
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
cd
}
fun_bar 'finish_ist'
clear
echo -e "\033[1;31m INSTALAÇÃO CONCLUÍDA!\033[0m"
echo ""
echo -ne "\033[1;33mSEU NS:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;33mSUA CHAVE PÚBLICA:\033[0m " && cat /root/server.pub
echo ""
echo -e "\033[1;33m SUA CHAVE ESTÁ SALVA NO ARQUIVO /root/server.pub\033[0m"
echo -e "\033[1;33mMANTENHA-A EM UM LOCAL SEGURO, VOCÊ PODE PRECISAR DELA NO FUTURO!\033[0m"
echo ""
read -p "Pressione [Enter] para voltar ao menu ou CTRL+C para sair"
slowdns
}
opc_key2 () {
echo -e "BAIXANDO PAR DE CHAVES PADRÃO..."
cd
wget https://raw.githubusercontent.com/PhoenixxZ2023/PLUS/main/Slowdns/server.key
wget https://raw.githubusercontent.com/PhoenixxZ2023/PLUS/main/Slowdns/server.pub
sleep 1
echo -e "Download Concluído"
sleep 1
cd /etc/slowdns/
echo -e "FINALIZANDO..."
finish_ist () {
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
cd
}
fun_bar 'finish_ist'
clear
echo -e "\033[1;31m INSTALAÇÃO CONCLUÍDA!\033[0m"
echo ""
echo -ne "\033[1;33mSEU NS:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;33mSUA CHAVE PÚBLICA:\033[0m " && cat /root/server.pub
echo ""
echo -e "\033[1;33m SUA CHAVE está salva no arquivo /root/server.pub\033[0m"
echo -e "\033[1;33mMANTENHA-A EM UM LOCAL SEGURO, VOCÊ PODE PRECISÁ-LA NO FUTURO!\033[0m"
echo ""
read -p "Pressione [Enter] para retornar ao menu ou CTRL+C para sair"
slowdns
}

opc_keyx () {
    echo "Abortando a instalação"
    sleep 2
    slowdns
}

key_gen
fi
