#!/bin/bash
# Definir variáveis para cores de texto
RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
PURPLE='\033[1;35m'
CYAN='\033[1;36m'
GRAY='\033[1;37m'
WHITE='\033[1;37m'
# Definir variáveis para cores de fundo
BG_RED='\033[0;41m'
BG_GREEN='\033[0;42m'
BG_YELLOW='\033[0;43m'
BG_BLUE='\033[0;44m'
BG_PURPLE='\033[0;45m'
BG_CYAN='\033[0;46m'
BG_GRAY='\033[0;47m'
# Resetar cores
RESET='\033[0m'

# Exibindo cabeçalho com o título em maiúsculas e negrito
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ───────────────── /// ────────────────── ${YELLOW}"
figlet -p -f slant SLOWDNS
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ─────────────── SLOWDNS ──────────────── ${YELLOW}"

# Exibindo informações do SlowDNS em maiúsculas e negrito
echo -e "${GREEN}INFORMAÇÕES DO SLOWDNS!"
echo ""
echo -ne "${YELLOW}SEU NS: ${WHITE}" && cat /etc/slowdns/infons
echo -ne "${YELLOW}SUA CHAVE PÚBLICA: ${WHITE}" && cat /root/server.pub
echo ""

# Mensagem de alerta sobre a chave em maiúsculas e negrito
echo -e "${YELLOW}SUA CHAVE ESTÁ SALVA NO ARQUIVO /ROOT/SERVER.PUB${RESET}"
echo -e "${YELLOW}MANTENHA-A EM UM LOCAL SEGURO, VOCÊ PODE PRECISÁ-LA NO FUTURO!${RESET}"
echo ""

# Pedir ao usuário para continuar em maiúsculas e negrito
echo -e "${YELLOW}› PRESSIONE ENTER PARA CONTINUAR${RESET}"
read -p " "

# Chamada para o script slowdns
slowdns
