#!/bin/bash
#SlowDNS @PowerMX
# Definir variáveis para cores de texto
IP=$(curl -s -4 icanhazip.com)
HOST=`hostname`
RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
PURPLE='\033[1;35m'
CYAN='\033[1;36m'
GRAY='\033[1;37m'
WHITE='\033[1;37m'
# Definir variáveis para cores de fundo
BG_RED='\033[0;41m'
BG_GREEN='\033[0;42m'
BG_YELLOW='\033[0;43m'
BG_BLUE='\033[0;44m'
BG_PURPLE='\033[0;45m'
BG_CYAN='\033[0;46m'
BG_GRAY='\033[0;47m'
# Resetar cores
RESET='\033[0m'

slowdns () {
tput reset
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ───────────────── /// ────────────────── ${YELLOW}"
figlet -p -f slant SlowDNS
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ────────── MOD SLOWDNS VPSPACK ───────── ${YELLOW}"
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ──        TELEGRAM: @VPNMX           ── ${YELLOW}"
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ──            @PowerMX              ── ${YELLOW}"
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ───────────────── /// ────────────────── ${RESET}"
echo -e "${YELLOW}IP DO SERVIDOR: ${WHITE}$IP\033[0m "
echo -e "${YELLOW}NOME DO HOST: ${WHITE}$HOST\033[0m "
arquivo="/etc/slowdns/infons"
if [ -e "$arquivo" ]; then
    echo -ne "${YELLOW}SEU NS: ${WHITE} " && cat /etc/slowdns/infons
    echo -ne "${YELLOW}SUA CHAVE PÚBLICA:\033[0m " && cat /root/server.pub
else
    echo -e "${RED}NÃO INSTALADO\033[0m"
fi
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ───────────────── /// ────────────────── ${YELLOW}"
    echo -e "\033[1m${YELLOW}[${GREEN}01${YELLOW}]${WHITE} | INSTALAR SLOWDNS SSH\033[0m"
    echo -e "\033[1m${YELLOW}[${GREEN}02${YELLOW}]${WHITE} | INSTALAR SLOWDNS SSL\033[0m"
    echo -e "\033[1m${YELLOW}[${GREEN}03${YELLOW}]${WHITE} | INSTALAR SLOWDNS DROPBEAR\033[0m"
    echo -e "\033[1m${YELLOW}[${GREEN}04${YELLOW}]${WHITE} | INSTALAR SLOWDNS SOCKS\033[0m"
    echo -e "\033[1m${YELLOW}[${GREEN}05${YELLOW}]${WHITE} | INSTALAR SLOWDNS SERVIÇO PERSONALIZADO\033[0m"
    echo -e "\033[1m${YELLOW}[${GREEN}06${YELLOW}]${WHITE} | VER INFORMAÇÕES\033[0m"
    echo -e "\033[1m${YELLOW}[${GREEN}07${YELLOW}]${WHITE} | INICIAR SLOWDNS\033[0m"
    echo -e "\033[1m${YELLOW}[${GREEN}08${YELLOW}]${WHITE} | REINICIAR SLOWDNS\033[0m"
    echo -e "\033[1m${YELLOW}[${GREEN}09${YELLOW}]${WHITE} | PARAR SLOWDNS\033[0m"
    echo -e "\033[1m${YELLOW}[${GREEN}10${YELLOW}]${WHITE} | REMOVER SLOWDNS\033[0m"
    echo -e "\033[1m${YELLOW}[${GREEN}11${YELLOW}]${WHITE} | ATUALIZAR/REINSTALAR\033[0m"
    echo -e "\033[1m${YELLOW}[${GREEN}12${YELLOW}]${WHITE} | REMOVER SCRIPT\033[0m"
    echo -e "\033[1m${YELLOW}[${GREEN}00${YELLOW}]${WHITE} | SAIR\033[0m"
    echo ""
    echo -ne "\033[1m${YELLOW}O QUE DESEJA FAZER?:\0033[m " && read option
    case $option in
    1) Option1 ;;
    2) Option2 ;;
    3) Option3 ;;
    4) Option4 ;;
    5) Option5 ;;
    6) Option6 ;;
    7) Option7 ;;
    8) Option8 ;;
    9) Option9 ;;
    10) Option10 ;;
    11) Option11 ;;
    12) Option12 ;;
    0) Sair ;;
    *) "OPÇÃO INVÁLIDA" ; echo ; slowdns ;;
    esac
}

Option1 () {
    clear
    bash /etc/slowdns/slowdns-ssh
    slowdns
}

Option2 () {
    clear
    bash /etc/slowdns/slowdns-ssl
    slowdns
}

Option3 () {
    clear
    bash /etc/slowdns/slowdns-drop
    slowdns
}

Option4 () {
    clear
    bash /etc/slowdns/slowdns-socks
}

Option5 () {
    clear
    bash /etc/slowdns/slowdns-customservice
    slowdns
}

Option6 () {
    clear
    bash /etc/slowdns/slowdns-info
}

Option7 () {
    clear
    bash /etc/slowdns/startdns
    echo -e "\033[1;33m › PRESSIONE ENTER PARA CONTINUAR\033[0m"
    read -p " "
    slowdns
}

Option8 () {
    clear
    bash /etc/slowdns/restartdns
    echo -e "\033[1;33m › PRESSIONE ENTER PARA CONTINUAR\033[0m"
    read -p " "
    slowdns
}

Option9 () {
    clear
    bash /etc/slowdns/stopdns
    echo -e "\033[1;33m › PRESSIONE ENTER PARA CONTINUAR\033[0m"
    read -p " "
    slowdns
}

Option10 () {
    clear
    bash /etc/slowdns/stopdns
    bash /etc/slowdns/remove-slow
    echo -e "\033[1;33m › PRESSIONE ENTER PARA CONTINUAR\033[0m"
    read -p " "
    menu
}

Option11 () {
    clear
    wget https://raw.githubusercontent.com/PhoenixxZ2023/PLUS/main/Slowdns/update
    chmod +x update
    bash update
}

Option12 () {
    clear
    bash /etc/slowdns/remove-slow
    echo -e "\033[0;31mGERENCIADOR SLOWDNS DESINSTALADO!\033[0m"
    sleep 3
    rm /bin/slowdns
    echo -e "\033[1;33m › PRESSIONE ENTER PARA CONTINUAR\033[0m"
    read -p " "
    menu
}

Sair() {
    clear
    menu
}

clear
slowdns
